### ISSUE TITLE
Need VBA code help for birthday emails to team

### ISSUE THREAD

**Issue by vamsimantripragada** [deepaklohia/ExcelBirthdayAutomation#1]
Hi Deepak,

I need help in VBA code as per attached screenshot.
In the template I want to change **Employee picture** and **First Name** to be dynamically picked from excel file on their respective birthday date.

![image](https://user-images.githubusercontent.com/97298277/148560154-1bbf5eb4-050d-4b13-9042-64a6025c1166.png)

**Comment by deepaklohia** [comment]
For custom requests watch YouTube video carefully . You should be able to make changes by adding a custom textbox and giving it a reference name . Thanks
